'''
Author: LetMeFly
Date: 2026-07-30 14:49:28
LastEditors: LetMeFly.xyz
LastEditTime: 2026-07-30 18:03:15
Description: 不借助zip工具生成.livp
Description: All Writen By Hand
Description: What A Beautiful Design(bushi
'''
from sys import argv
from io import BufferedWriter
from os.path import getmtime, basename
from time import localtime
from struct import pack
from zlib import crc32


class File:
    def __init__(self, filename: str):
        self.filename = filename
        self.name = basename(filename).encode("utf-8")
        self.size = 0
        self.crc32 = 0
        self.data = b""  # 先给干内存里得了。
        self.offset = 0  # 文件头起始位置在zip文件里的偏移量
    
    def get_dos_datetime(self) -> tuple[int, int]:
        t = localtime(getmtime(self.filename))
        year = min(max(t.tm_year, 1980), 2107)  #仅支持1980-2197年
        dos_time = (t.tm_hour << 11) | (t.tm_min << 5) | (t.tm_sec // 2)
        dos_date = ((year - 1980) << 9) | (t.tm_mon << 5) | t.tm_mday
        return dos_time, dos_date
    
    def get_crc32(self) -> int:
        if self.crc32:
            return self.crc32
        return self.__calc_crc32()
    
    def get_data(self) -> bytes:
        if not self.data:
            with open(self.filename, "rb") as f:
                self.data = f.read()
        return self.data

    def get_size(self) -> int:
        if not self.size:
            self.size = len(self.get_data())
        return self.size
    
    def __calc_crc32(self) -> int:
        data = self.get_data()
        self.crc32 = crc32(data) & 0xffffffff  # 只取32位（&0xffffffff是为了兼容python2写法）
        return self.crc32


class Zip:
    def __init__(self, *files: File):
        self.files = files
        self.comment = self.t()
        self.cd_len = 0  # 中央目录总长度
    
    def t(self) -> bytes:
        # 这样是为了方便后面的拓展
        return ZipCommenter.create(self.files).get_comment()

    def _write1file(self, file: File, out: BufferedWriter):
        file.offset = out.tell()
        dos_time, dos_date = file.get_dos_datetime()
        # 现在支持的版本标志位=0x0000，要么读两遍文件，要么seek回来覆盖掉crc32，暂时选择读两遍文件
        crc32 = file.get_crc32()
        size = file.get_size()
        out.write(pack(
            "<IHHHHHIIIHH",
            0x04034b50,      # 签名
            0x0014,          # 版本2.0
            0x0000,          # 标志位
            0x0000,          # 压缩方法(仅存储)
            dos_time,        # 修改时间
            dos_date,        # 修改日期
            crc32,           # CRC32
            size,            # 压缩大小
            size,            # 原始大小
            len(file.name),  # 文件名长度
            0x0000           # 额外字段长度
        ))
        out.write(file.name)
        out.write(file.get_data())
    
    def _write_central_directory(self, file: File, out: BufferedWriter):
        dos_time, dos_date = file.get_dos_datetime()
        crc32 = file.get_crc32()
        size = file.get_size()
        out.write(pack(
            "<IHHHHHHIIIHHHHHII",
            0x02014b50,      # 签名
            0x0000,          # 创建此文件所用版本
            0x0014,          # 提取所需最低版本，同 Local Header(版本2.0)
            0x0000,          # 标志位
            0x0000,          # 压缩方法(仅存储)
            dos_time,        # 修改时间
            dos_date,        # 修改日期
            crc32,           # CRC32
            size,            # 压缩大小
            size,            # 原始大小
            len(file.name),  # 文件名长度
            0x0000,          # 额外字段长度
            0x0000,          # 文件注释长度
            0x0000,          # 磁盘号
            0x0000,          # 内部文件属性
            0x00000000,      # 外部文件属性
            file.offset      # 文件头起始位置在zip文件中的偏移量
        ))
        out.write(file.name)
        self.cd_len += 46 + len(file.name)
    
    def _write_end_of_central_directory(self, out: BufferedWriter):
        out.write(pack(
            "<IHHHHIIH",
            0x06054b50,                # 签名
            0x0000,                    # 磁盘号
            0x0000,                    # 中央目录起始磁盘号
            len(self.files),           # 本磁盘上中央目录记录数   
            len(self.files),           # 中央目录记录总数
            self.cd_len,               # 中央目录大小
            out.tell() - self.cd_len,  # 中央目录起始位置相对于起始磁盘的偏移量
            len(self.comment)          # zip文件注释长度
        ))
    

    def _write_comment(self, out: BufferedWriter):
        out.write(self.comment)

    def write(self, output: str):
        with open(output, "wb") as out:
            for file in self.files:
                self._write1file(file, out)
            for file in self.files:
                self._write_central_directory(file, out)
            self._write_end_of_central_directory(out)
            self._write_comment(out)


class ZipCommenter:
    def get_comment(self) -> bytes:
        return b"generated by LetMeFly.xyz"

    @staticmethod
    def create(files: list[File]) -> "ZipCommenter":
        if len(files) == 2:
            return LivpCommenter(files[0], files[1])
        return ZipCommenter()


class LivpCommenter(ZipCommenter):
    def __init__(self, static_file: File, dynamic_file: File):
        self.static_file = static_file
        self.dynamic_file = dynamic_file
        self.static_file_type = self.static_file.name.rsplit(b".", 1)[-1].lower()
        assert self.static_file_type in [b"jpg", b"jpeg", b"heic"]
        self.dynamic_file_type = self.dynamic_file.name.rsplit(b".", 1)[-1].lower()
        assert self.dynamic_file_type in [b"mov"]
    
    @staticmethod
    def _val(val: int, length: int) -> str:
        return f"{val:0{length}X}"
    
    def get_comment(self) -> bytes:
        comment = ""
        if self.static_file_type == b"heic":
            comment += self._val(2, 4)
        elif self.static_file_type in [b"jpg", b"jpeg"]:
            comment += self._val(5, 4)
        comment += self._val(30 + len(self.static_file.name), 8)
        comment += self._val(self.static_file.get_size(), 8)
        if self.dynamic_file_type == b"mov":
            comment += self._val(3, 4)
        comment += self._val(
            self.static_file.get_size()
            + 30 + len(self.static_file.name)
            + 30 + len(self.dynamic_file.name),
            8
        )
        comment += self._val(self.dynamic_file.get_size(), 8)
        comment += "313030304C495650"
        return comment.encode("ascii")

def help(filename: str):
    print(f"Usage: python {filename} <static_file> <dynamic_file> <output_file>")


if __name__ == "__main__":
    if len(argv) != 4:
        print("there must be 3 arguments, but got %d" % (len(argv) - 1))
        help(argv[0])
        exit(1)    
    zip = Zip(File(argv[1]), File(argv[2]))
    zip.write(argv[3])
